In [2]:
import cv2

In [3]:
photo=cv2.imread('Payal.jpg')

In [4]:
cv2.imshow('Me', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
photo.shape

(593, 443, 3)

In [6]:
photo

array([[[156, 150, 131],
        [142, 141, 127],
        [126, 128, 122],
        ...,
        [117, 118, 116],
        [136, 136, 136],
        [130, 134, 135]],

       [[154, 147, 127],
        [137, 136, 122],
        [151, 153, 147],
        ...,
        [109, 110, 108],
        [127, 129, 129],
        [126, 130, 131]],

       [[165, 158, 138],
        [104, 101,  87],
        [112, 116, 111],
        ...,
        [111, 112, 110],
        [127, 129, 129],
        [128, 132, 133]],

       ...,

       [[210, 218, 218],
        [207, 215, 215],
        [202, 210, 210],
        ...,
        [110, 125, 117],
        [158, 173, 165],
        [195, 210, 202]],

       [[210, 218, 218],
        [208, 216, 216],
        [214, 222, 222],
        ...,
        [174, 191, 182],
        [109, 126, 117],
        [175, 192, 183]],

       [[203, 213, 213],
        [201, 211, 211],
        [205, 215, 215],
        ...,
        [197, 214, 205],
        [162, 179, 170],
        [116, 133, 124]]

In [9]:
newphoto = cv2.cvtColor( photo , cv2.COLOR_BGR2GRAY )

In [11]:
cv2.imshow('Me', newphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
newphoto.shape

(593, 443)

In [13]:
newphoto

array([[145, 137, 126, ..., 117, 136, 134],
       [142, 132, 151, ..., 109, 129, 130],
       [153,  97, 114, ..., 111, 129, 132],
       ...,
       [217, 214, 209, ..., 121, 169, 206],
       [217, 215, 221, ..., 186, 121, 187],
       [212, 210, 214, ..., 209, 174, 128]], dtype=uint8)

In [26]:
cphoto=newphoto[250:380,150:280]

In [28]:
cv2.imshow('Me', cphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
import numpy as np

In [15]:
c=np.zeros((200,200))+0

In [20]:
cv2.imshow('Me', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
c

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])